repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks

      rev: v3.4.0
      hooks:
        - id: check-added-large-files
        - id: check-ast
        - id: check-builtin-literals
        - id: check-yaml
        - id: check-case-conflict
        - id: check-docstring-first
        - id: check-json
        - id: check-merge-conflict
        - id: detect-private-key
#        - id: double-quote-string-fixer
        - id: end-of-file-fixer
        - id: requirements-txt-fixer
    - repo: https://github.com/psf/black
      rev: 20.8b1
      hooks:
        - id: black
    - repo: https://github.com/timothycrosley/isort
      rev: 5.8.0
      hooks:
        - id: isort
    - repo: https://gitlab.com/pycqa/flake8
      rev:  3.9.0
      hooks:
        - id: flake8
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.812
      hooks:
        - id: mypy
