version: "3.7"

services:
  db:
    image: postgres
    hostname: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
  web:
    build: .
#    command: python manage.py
    env_file: .env
    user: root
    volumes:
      - .:/code
    ports:
      - "5000:5000"
      - "5001:5001"
      - "8000:8000"
    depends_on:
      - db
