version: "3.7"

services:
  db:
    image: postgres
    hostname: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
  web:
    build: .
    dockerfile: Dockerfile
#    command: python manage.py
    env_file: .env
    user: root
    entrypoint:
      - flask db init
      - flask db migrate
      - flask db migrate
      - python data_to_db.py
      - gunicorn --bind 0.0.0.0:8000  --workers=1 application
    volumes:
      - .:/code
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - db
