# Generated by Django 2.0.6 on 2018-06-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metro',
            name='exit_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
