# Generated by Django 2.0.6 on 2018-07-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0002_metro_exit_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetroStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('source_id', models.TextField(blank=True, null=True)),
                ('source_name', models.TextField(blank=True, null=True)),
                ('station_name', models.TextField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
