# Generated by Django 2.0.6 on 2018-07-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0003_metrostation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('points', models.TextField(blank=True, null=True)),
                ('eng_name', models.TextField(blank=True, null=True)),
                ('nat_name', models.TextField(blank=True, null=True)),
                ('scale', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
