# Generated by Django 2.0.6 on 2018-07-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0005_auto_20180707_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygonmodel',
            name='sale_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
