# Generated by Django 2.0.6 on 2018-07-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0006_polygonmodel_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygonmodel',
            name='nat_class_stat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
