# Generated by Django 2.0.6 on 2018-07-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0007_polygonmodel_nat_class_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat0', models.FloatField(blank=True, null=True)),
                ('lon0', models.FloatField(blank=True, null=True)),
                ('lat1', models.FloatField(blank=True, null=True)),
                ('lon1', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('mode', models.CharField(default='', max_length=30)),
                ('att', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
