# Generated by Django 2.0.6 on 2018-07-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0008_rawline'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat0', models.FloatField(blank=True, null=True)),
                ('lon0', models.FloatField(blank=True, null=True)),
                ('lat1', models.FloatField(blank=True, null=True)),
                ('lon1', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('mode', models.CharField(default='', max_length=30)),
                ('att', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='rawline',
            name='att',
        ),
        migrations.RemoveField(
            model_name='rawline',
            name='lat0',
        ),
        migrations.RemoveField(
            model_name='rawline',
            name='lat1',
        ),
        migrations.RemoveField(
            model_name='rawline',
            name='lon0',
        ),
        migrations.RemoveField(
            model_name='rawline',
            name='lon1',
        ),
        migrations.RemoveField(
            model_name='rawline',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='rawline',
            name='weight',
        ),
        migrations.AddField(
            model_name='rawline',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
