# Generated by Django 2.0.6 on 2018-07-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0009_auto_20180709_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawline',
            name='att',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='rawline',
            name='lat0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawline',
            name='lat1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawline',
            name='lon0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawline',
            name='lon1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawline',
            name='mode',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='rawline',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
