# Generated by Django 2.0.6 on 2018-07-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0010_auto_20180709_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationManyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.TextField(blank=True, null=True)),
                ('source_name', models.TextField(blank=True, null=True)),
                ('eng_class', models.TextField(blank=True, null=True)),
                ('nat_class', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
