# Generated by Django 2.0.6 on 2018-07-22 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0011_organizationmanytype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='eng_class',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='nat_class',
        ),
    ]
