# Generated by Django 2.0.6 on 2018-07-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0012_auto_20180722_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationNatClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.TextField(blank=True, null=True)),
                ('source_name', models.TextField(blank=True, null=True)),
                ('nat_class', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='OrganizationManyType',
        ),
    ]
