# Generated by Django 2.0.6 on 2018-07-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0013_auto_20180722_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationnatclass',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationnatclass',
            name='chain_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationnatclass',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationnatclass',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
