# Generated by Django 2.0.6 on 2018-08-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0015_groundstop_workplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='nearest_nat_classes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
