# Generated by Django 2.0.6 on 2018-08-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0016_house_nearest_nat_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundstop',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groundstop',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metro',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metro',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metrostation',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metrostation',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationnatclass',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationnatclass',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workplace',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workplace',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
