# Generated by Django 2.0.6 on 2018-08-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0017_auto_20180803_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperSquare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_home', models.NullBooleanField()),
                ('male', models.NullBooleanField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('income', models.IntegerField(blank=True, null=True)),
                ('users', models.IntegerField(blank=True, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
