# Generated by Django 2.0.6 on 2018-08-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0018_opersquare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opersquare',
            name='age',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opersquare',
            name='income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opersquare',
            name='users',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
