# Generated by Django 2.0.6 on 2018-08-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0019_auto_20180806_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='opersquare',
            name='source_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
