# Generated by Django 2.0.6 on 2018-08-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0020_opersquare_source_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='nearest_nat_classes',
            new_name='nearest_nat_classes_euclid',
        ),
    ]
