# Generated by Django 2.0.6 on 2018-08-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0021_auto_20180809_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='nearest_nat_classes_metro_euclid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
