# Generated by Django 2.0.6 on 2018-08-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0022_house_nearest_nat_classes_metro_euclid'),
    ]

    operations = [
        migrations.AddField(
            model_name='linemodel',
            name='n_parts',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
