# Generated by Django 2.0.6 on 2018-08-14 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0024_salepoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salepoint',
            old_name='revenue',
            new_name='pred_revenue',
        ),
    ]
