# Generated by Django 2.0.6 on 2018-08-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0025_auto_20180814_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salepoint',
            old_name='pred_revenue',
            new_name='revenue_pred',
        ),
    ]
