# Generated by Django 2.0.6 on 2018-08-17 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0027_predicredsquare'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PredicredSquare',
            new_name='PredictedSquare',
        ),
    ]
