# Generated by Django 2.0.6 on 2018-08-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0028_auto_20180817_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salepoint',
            name='revenue_pred',
        ),
        migrations.AddField(
            model_name='salepoint',
            name='revenue_pred_model1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salepoint',
            name='revenue_pred_model2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
