# Generated by Django 2.0.6 on 2018-08-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0029_auto_20180817_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='revenue_pred_model1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='revenue_pred_model2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
