# Generated by Django 2.0.6 on 2018-08-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0030_auto_20180818_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='machine_features',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
