# Generated by Django 2.0.6 on 2018-08-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0031_organization_machine_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationnatclass',
            name='machine_features',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationnatclass',
            name='revenue_pred_model1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationnatclass',
            name='revenue_pred_model2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
