# Generated by Django 2.0.6 on 2018-08-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0032_auto_20180818_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='machine_features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
