# Generated by Django 2.0.6 on 2018-08-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0033_auto_20180818_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='chain_name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='info',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='machine_features',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='revenue_pred_model1',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='revenue_pred_model2',
        ),
        migrations.AlterField(
            model_name='organizationnatclass',
            name='machine_features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
