# Generated by Django 2.0.6 on 2018-08-18 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0034_auto_20180818_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationnatclass',
            name='machine_features',
        ),
        migrations.RemoveField(
            model_name='organizationnatclass',
            name='revenue_pred_model1',
        ),
        migrations.RemoveField(
            model_name='organizationnatclass',
            name='revenue_pred_model2',
        ),
    ]
