# Generated by Django 2.0.6 on 2018-08-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0035_auto_20180818_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salepoint',
            name='machine_features',
        ),
        migrations.RemoveField(
            model_name='salepoint',
            name='revenue_pred_model1',
        ),
        migrations.RemoveField(
            model_name='salepoint',
            name='revenue_pred_model2',
        ),
        migrations.AddField(
            model_name='salepoint',
            name='cann',
            field=models.TextField(blank=True, null=True),
        ),
    ]
