# Generated by Django 2.0.6 on 2018-08-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0036_auto_20180818_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepoint',
            name='machine_features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salepoint',
            name='revenue_pred_model1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salepoint',
            name='revenue_pred_model2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
