# Generated by Django 2.0.6 on 2018-08-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0037_auto_20180818_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepoint',
            name='isocrone_coords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salepoint',
            name='isocrone_times',
            field=models.TextField(blank=True, null=True),
        ),
    ]
