# Generated by Django 2.1.1 on 2018-09-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0038_auto_20180819_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id1', models.TextField(blank=True, null=True)),
                ('source_name1', models.TextField(blank=True, null=True)),
                ('source_id2', models.TextField(blank=True, null=True)),
                ('source_name2', models.TextField(blank=True, null=True)),
                ('nat_class', models.TextField(blank=True, null=True)),
                ('euclid_distance', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
