# Generated by Django 2.1.1 on 2018-09-04 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0039_distances'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Distances',
            new_name='Distance',
        ),
    ]
