# Generated by Django 2.1.1 on 2018-09-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0040_auto_20180904_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='euclid_distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
