# Generated by Django 2.1.1 on 2018-09-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0041_auto_20180904_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='source_id1',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
