# Generated by Django 2.1.1 on 2018-09-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0042_auto_20180905_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opersquare',
            name='age',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='opersquare',
            name='if_home',
            field=models.NullBooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='opersquare',
            name='income',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='opersquare',
            name='male',
            field=models.NullBooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='opersquare',
            name='x',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='opersquare',
            name='y',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
