# Generated by Django 2.1.1 on 2018-09-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0044_auto_20180905_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='nat_class',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='distance',
            name='source_id2',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='distance',
            name='source_name1',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='distance',
            name='source_name2',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationnatclass',
            name='chain_name',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationnatclass',
            name='nat_class',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
