# Generated by Django 2.1.1 on 2018-09-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0045_auto_20180906_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(blank=True, db_index=True, null=True)),
                ('y', models.FloatField(blank=True, db_index=True, null=True)),
                ('lon', models.FloatField(blank=True, db_index=True, null=True)),
                ('lat', models.FloatField(blank=True, db_index=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('source_id1', models.TextField(blank=True, null=True)),
                ('source_name1', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
