# Generated by Django 2.1.1 on 2018-09-06 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0046_cities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cities',
            new_name='City',
        ),
    ]
