# Generated by Django 2.1.1 on 2018-09-06 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0047_auto_20180906_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='source_id1',
            new_name='source_id',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='source_name1',
            new_name='source_name',
        ),
    ]
