# Generated by Django 2.1.1 on 2018-09-15 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0049_auto_20180906_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceTemp',
            fields=[
                ('distance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_map.Distance')),
            ],
            bases=('main_map.distance',),
        ),
    ]
