# Generated by Django 2.1.1 on 2018-11-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0050_distancetemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSquare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(blank=True, db_index=True, null=True)),
                ('y', models.FloatField(blank=True, db_index=True, null=True)),
                ('driving', models.FloatField(blank=True, null=True)),
                ('foor', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='salepoint',
            name='comp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
