# Generated by Django 2.1.1 on 2018-11-16 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0051_auto_20181116_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesquare',
            old_name='foor',
            new_name='foot',
        ),
    ]
