# Generated by Django 2.1.1 on 2018-12-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0052_auto_20181116_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimePolygons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(blank=True, db_index=True, null=True)),
                ('y', models.FloatField(blank=True, db_index=True, null=True)),
                ('time', models.FloatField(blank=True, db_index=True, null=True)),
                ('geojson', models.TextField(blank=True, null=True)),
                ('cafe', models.NullBooleanField()),
            ],
        ),
    ]
