# Generated by Django 2.1.1 on 2018-12-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0054_alcostopper'),
    ]

    operations = [
        migrations.AddField(
            model_name='alcostopper',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
