# Generated by Django 2.1.1 on 2018-12-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0055_alcostopper_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='alcostopper',
            name='lat',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='alcostopper',
            name='lon',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
