# Generated by Django 2.1.1 on 2018-12-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0057_auto_20181208_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='alcostopper',
            name='cafe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
