# Generated by Django 2.1.1 on 2018-12-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0059_auto_20181208_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictedsquare',
            name='alco_stopper_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
