# Generated by Django 2.1.1 on 2018-12-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0060_predictedsquare_alco_stopper_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictedsquare',
            name='alco_stopper_id',
        ),
        migrations.AddField(
            model_name='timepolygons',
            name='alco_stopper_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
