# Generated by Django 2.1.1 on 2018-12-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0061_auto_20181208_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='timepolygons',
            name='geojson_smoothed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
