# Generated by Django 2.1.1 on 2018-12-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_map', '0062_timepolygons_geojson_smoothed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimePolygonsUnion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(blank=True, db_index=True, null=True)),
                ('y', models.FloatField(blank=True, db_index=True, null=True)),
                ('time', models.FloatField(blank=True, db_index=True, null=True)),
                ('geojson', models.TextField(blank=True, null=True)),
                ('geojson_smoothed', models.TextField(blank=True, null=True)),
                ('cafe', models.NullBooleanField()),
                ('alco_stopper_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='timepolygons',
            name='time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
